// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the tlRender project.

#pragma once

#define TLRENDER_VERSION_MAJOR 0
#define TLRENDER_VERSION_MINOR 20
#define TLRENDER_VERSION_PATCH 0
#define TLRENDER_VERSION_DEV "-dev"

#define TLRENDER_VERSION_STR_(x) #x
#define TLRENDER_VERSION_STR(x) TLRENDER_VERSION_STR_(x)
#define TLRENDER_VERSION_FULL \
    TLRENDER_VERSION_STR(TLRENDER_VERSION_MAJOR) "." \
    TLRENDER_VERSION_STR(TLRENDER_VERSION_MINOR) "." \
    TLRENDER_VERSION_STR(TLRENDER_VERSION_PATCH) TLRENDER_VERSION_DEV
